# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Generate a generic latin square
#'
#' @param labels The labels to be filled in as values in the latin square.
#' @export
generic_square <- function(labels) {
    .Call(`_funfact_generic_square`, labels)
}

#' Generate a digram-balanced latin square for even n
#'
#' @param labels The labels to be filled in as values in the latin square.
#' @export
digram_square_even <- function(labels) {
    .Call(`_funfact_digram_square_even`, labels)
}

#' Generate a digram-balanced latin squares for odd n
#' 
#' @param labels The labels to be filled in as values in the latin square.
#' @export
digram_square_odd <- function(labels) {
    .Call(`_funfact_digram_square_odd`, labels)
}

#' Generate an alimena square
#'
#' @param labels The labels to be filled in as values in the latin square.
#' @export
alimena_square <- function(labels) {
    .Call(`_funfact_alimena_square`, labels)
}

all_permutations <- function(labels) {
    .Call(`_funfact_all_permutations`, labels)
}

prs_factor <- function(labels, nreps, maxrun = 0L) {
    .Call(`_funfact_prs_factor`, labels, nreps, maxrun)
}

