# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

alimena_square <- function(labels) {
    .Call(`_funfact_alimena_square`, labels)
}

prs_factor <- function(labels, nreps, maxrun = 0L) {
    .Call(`_funfact_prs_factor`, labels, nreps, maxrun)
}

